version: "3.7"

services:
    mysql:
        image: mysql
        container_name: ${DB_DATABASE}
        ports:
            - 3306:3306
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - intern_manager:/var/lib/mysql

    laravel:
        build: .
        env_file: .env
        ports:
            - 8000:80
        volumes:
            - .:/var/www/html/

volumes:
    intern_manager:
