version: "3.7"

services:
    mysql:
        image: mysql
        ports:
            - 3307:3306
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USERNAME: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - intern_manager:/var/lib/mysql

    laravel:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        ports:
            - 8009:80
        volumes:
            - .:/var/www/html/
        depends_on:
            - mysql
    #         - laravel-init

    # laravel-init:
    #     build:
    #         context: .
    #         target: php
    #         args:
    #             - APP_ENV=${APP_ENV}
    #     environment:
    #         - APP_ENV=${APP_ENV}
    #         - CONTAINER_ROLE=app
    #     command: Docker/entrypoint.sh
    #     volumes:
    #         - .:/var/www/html/
    #     depends_on:
    #         - mysql

volumes:
    intern_manager:
